//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlBlocksChildren
    {
        public System.Guid SiteBlockChildsId { get; set; }
        public System.Guid SiteBlockId { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string CSSClass { get; set; }
        public Nullable<decimal> ChildOrder { get; set; }
    
        public virtual HtmlBlocks HtmlBlocks { get; set; }
    }
}
