//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlBlocksChildren
    {
        public System.Guid SiteBlockChildsId { get; set; }
        public System.Guid SiteBlockId { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string CSSClass { get; set; }
        public Nullable<int> ChildOrder { get; set; }
    
        public virtual HtmlBlocks HtmlBlocks { get; set; }
    }
}
