//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlBlocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HtmlBlocks()
        {
            this.HtmlBlocksChildren = new HashSet<HtmlBlocksChildren>();
        }
    
        public System.Guid SiteBlockId { get; set; }
        public string ParentCSSClass { get; set; }
        public string ParentTitle { get; set; }
        public string ChildCSSClass { get; set; }
        public string SitePage { get; set; }
        public Nullable<int> Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HtmlBlocksChildren> HtmlBlocksChildren { get; set; }
    }
}
