//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WowCarryEntities : DbContext
    {
        public WowCarryEntities()
            : base("name=WowCarryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductGame> ProductGame { get; set; }
        public virtual DbSet<ProductPrice> ProductPrice { get; set; }
        public virtual DbSet<ProductDescription> ProductDescription { get; set; }
        public virtual DbSet<ProductSubCategory> ProductSubCategory { get; set; }
        public virtual DbSet<HtmlBlocks> HtmlBlocks { get; set; }
        public virtual DbSet<HtmlBlocksChildren> HtmlBlocksChildren { get; set; }
        public virtual DbSet<Realms> Realms { get; set; }
        public virtual DbSet<OptionParams> OptionParams { get; set; }
        public virtual DbSet<ProductOption> ProductOption { get; set; }
        public virtual DbSet<SEO> SEO { get; set; }
        public virtual DbSet<ProductToOption> ProductToOption { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
