//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionParams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OptionParams()
        {
            this.ProductOption = new HashSet<ProductOption>();
        }
    
        public System.Guid OptionParamsId { get; set; }
        public string ParamName { get; set; }
        public string ParamTooltip { get; set; }
        public Nullable<double> ParamPrice { get; set; }
        public Nullable<System.Guid> ProductOptionId { get; set; }
        public string Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOption> ProductOption { get; set; }
        public virtual ProductOption ProductOption1 { get; set; }
    }
}
