//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public System.Guid OrderId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string Discord { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> OrderCustomFieldsId { get; set; }
        public string Email { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string OrderStatus { get; set; }
        public string Currency { get; set; }
        public string CustomerIP { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> OrderCreateTime { get; set; }
        public Nullable<System.DateTime> OrderUpdateTime { get; set; }
        public Nullable<bool> EmailSended { get; set; }
        public Nullable<System.DateTime> EmailSendTime { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual OrderCustomFields OrderCustomFields { get; set; }
    }
}
