//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCustomFields()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public System.Guid OrderCustomFieldsId { get; set; }
        public string ShlCharacterName { get; set; }
        public string ShlRealmName { get; set; }
        public string ShlFaction { get; set; }
        public string ShlRegion { get; set; }
        public string ShlBattleTag { get; set; }
        public string PoeCharacterName { get; set; }
        public string PoeAccountName { get; set; }
        public string ClassicCharacterName { get; set; }
        public string ClassicRealmName { get; set; }
        public string ClassicFaction { get; set; }
        public string ClassicRegion { get; set; }
        public string ClassicBattleTag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
