//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductToOption = new HashSet<ProductToOption>();
            this.ProductPrice = new HashSet<ProductPrice>();
        }
    
        public System.Guid ProductId { get; set; }
        public string ProductName { get; set; }
        public System.Guid ProductCategoryId { get; set; }
        public bool InStock { get; set; }
        public bool PreOrder { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public string ProductImage { get; set; }
        public System.DateTime ProductCreateDate { get; set; }
        public System.DateTime ProductUpdateDate { get; set; }
        public Nullable<System.Guid> ProductDescriptionId { get; set; }
        public Nullable<System.Guid> ProductSEOId { get; set; }
        public Nullable<System.Guid> ProductGameId { get; set; }
        public Nullable<System.Guid> ProductSubCategoryId { get; set; }
        public Nullable<int> ProductPriority { get; set; }
        public bool ProductEnabled { get; set; }
        public string ProductImageThumb { get; set; }
    
        public virtual ProductGame ProductGame { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual SEO SEO { get; set; }
        public virtual ProductDescription ProductDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductToOption> ProductToOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrice { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
