//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Product = new HashSet<Product>();
        }
    
        public System.Guid ProductCategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public Nullable<System.Guid> ProductGameId { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<System.Guid> ProductSubCategoryId { get; set; }
        public Nullable<System.Guid> CategorySeoId { get; set; }
    
        public virtual ProductGame ProductGame { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual SEO SEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
