//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOptionParams
    {
        public System.Guid OptionParamsId { get; set; }
        public string ParamName { get; set; }
        public string ParamTooltip { get; set; }
        public Nullable<double> ParamPrice { get; set; }
        public Nullable<System.Guid> ProductOptionId { get; set; }
        public string Sale { get; set; }
    
        public virtual ProductOptions ProductOptions { get; set; }
    }
}
