//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOptions
    {
        public System.Guid OptionId { get; set; }
        public string OptionName { get; set; }
        public string OptionType { get; set; }
        public Nullable<System.Guid> OptionParentId { get; set; }
        public Nullable<System.Guid> OptionProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
