//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Product = new HashSet<Product>();
        }
    
        public System.Guid ProductCategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public Nullable<System.Guid> ProductGameId { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<System.Guid> ProductSubCategoryId { get; set; }
        public Nullable<System.Guid> CategorySeoId { get; set; }
    
        public virtual ProductGame ProductGame { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual SEO SEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
