//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDescription()
        {
            this.Product = new HashSet<Product>();
        }
    
        public System.Guid ProductDescriptionId { get; set; }
        public string Description { get; set; }
        public string SubDescriptionTitle1 { get; set; }
        public string SubDescriptionTitle2 { get; set; }
        public string SubDescriptionTitle3 { get; set; }
        public string SubDescriptionTitle4 { get; set; }
        public string SubDescriptionTitle5 { get; set; }
        public string SubDescription1 { get; set; }
        public string SubDescription2 { get; set; }
        public string SubDescription3 { get; set; }
        public string SubDescription4 { get; set; }
        public string SubDescription5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
