//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductToOption
    {
        public System.Guid ProductId { get; set; }
        public System.Guid OptionId { get; set; }
    
        public virtual ProductOption ProductOption { get; set; }
        public virtual Product Product { get; set; }
    }
}
