//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realms
    {
        public System.Guid RealmId { get; set; }
        public System.Guid ProductGameId { get; set; }
        public string RealmName { get; set; }
    
        public virtual ProductGame ProductGame { get; set; }
    }
}
