//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateOptions()
        {
            this.TempOptionParams = new HashSet<TempOptionParams>();
        }
    
        public System.Guid TempOptionId { get; set; }
        public string TempOptionName { get; set; }
        public string TempOptionType { get; set; }
        public Nullable<System.Guid> TempOptionParamParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempOptionParams> TempOptionParams { get; set; }
        public virtual TempOptionParams TempOptionParams1 { get; set; }
    }
}
