//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOptionParams
    {
        public System.Guid ParameterId { get; set; }
        public string ParameterName { get; set; }
        public string ParameterTooltip { get; set; }
        public decimal ParameterPrice { get; set; }
        public Nullable<System.Guid> ParentOptionId { get; set; }
        public string ParameterSale { get; set; }
    
        public virtual TemplateOptions TemplateOptions { get; set; }
    }
}
