//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCarry.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string DefaultPage { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
